### PR TITLE
Feature 2 merge into master 

### PR DESCRIPTION
**Pull request by venkatasekher**
feature- 2 is developed , please review

### CODE REVIEW

**Comment by venkatasekher** [comment]
feature-2 is developed please review

**Comment by venkatasekher** [comment]
please review any changes are there

**Comment by chandrasekharyv** [comment]
> please review any changes are there

some changes are there like id and password make it clear

**Comment by venkatasekher** [comment]
> > please review any changes are there
> 
> some changes are there like id and password make it clear

modified the changes and please let me know for further changes

**Comment by chandrasekharyv** [comment]
> > > please review any changes are there
> > 
> > 
> > some changes are there like id and password make it clear
> 
> modified the changes and please let me know for further changes

seems to be good, no changes are required

**Pull request merged**
